### ISSUE TITLE
About the inputs of the decoders

### ISSUE THREAD

**Issue by SimZhou** [xueyouluo/fsauor2018#10]
`Inputs to decoder are learnable embeddings`

I assume the inputs to the decoders are one-hot vectors with dim 20 (e.g. decoder 1 input [1,0,0,...,0], decoder 2 input [0,1,0,0,...,0], etc.), and then transformed into embeddings by a learnable embedding layer, is this correct?

**Comment by xueyouluo** [comment]
Yes, you are right.

 

发件人: Simon Zhou <notifications@github.com>
答复: xueyouluo/fsauor2018 <reply@reply.github.com>
日期: 2020年4月3日 星期五 上午12:07
收件人: xueyouluo/fsauor2018 <fsauor2018@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [xueyouluo/fsauor2018] About the inputs of the decoders (#10)

 

Inputs to decoder are learnable embeddings

I assume the inputs to the decoders are one-hot vectors with dim 20 (e.g. decoder 1 input [1,0,0,...,0], decoder 2 input [0,1,0,0,...,0], etc.), and then transformed into embeddings by a learnable embedding layer, is this correct?
