### ISSUE TITLE
请问您如何处理那些不同类别数量极度不平衡的label？

### ISSUE THREAD

**Issue by viewlei** [xueyouluo/fsauor2018#3]
我们在预处理的时候发现，20个标签下，有的标签内98%的样本都被标记为-2（未提及），有的标签内仅有5%左右的样本被标记为0（中立）。我们的模型对于这些标签预测的结果比较差，也就是说对于那些出现次数很少的样本来说，预测结果特别差，召回率特别低，因此拉低了模型整体F1的结果。

看到您模型里使用了训练10个模型进行投票的方法，我这里想请教下您：

- 在训练这10个模型的时候，喂入的数据集是否相同？

- 您在训练这些类别数量极度不平衡的样本时采用了什么方法吗？
### 万分感谢！

**Comment by xueyouluo** [comment]
是的，这个数据的分布很不平衡，下面是我得到的每个类别的f1值：

| 类别 | f1 | precision | recall |
| ---- | ---- | ---- | ---- |
| location_traffic_convenience |0.6598383115674652| 0.6639170192784221| 0.684696525308326|
| location_distance_from_business_district |0.5701430669265533| 0.6418546149300068| 0.5671507122958691|
|location_easy_to_find |0.7144980306976957| 0.7461357294559532| 0.7063995224851409|
|service_wait_time |0.6639460048347786| 0.6797713566583926| 0.6508347188573869|
|service_waiters_attitude |0.7988629059090425| 0.8065592053400988| 0.796167406539511|
|service_parking_convenience |0.7358820751200599| 0.7478586952605837| 0.7397039057905653|
|service_serving_speed |0.777164216007539| 0.7827282028086737| 0.7745329868196769|
|price_level |0.7834244509601538| 0.776582688702729| 0.7922760732430886|
|price_cost_effective |0.7115463925525322| 0.7485854618631025| 0.6946224617022354|
|price_discount |0.6783785637176787| 0.6886596214927367| 0.673688385567519|
|environment_decoration |0.734927217936367| 0.7440601601549699| 0.7303315978775609|
|environment_noise |0.7633639406211334| 0.7817826501348686| 0.7523320401297642|
|environment_space |0.7621530462108181| 0.7552558832536221| 0.7700071722753337|
|environment_cleaness |0.7588325044668185| 0.7816683635764835| 0.7458392590539515|
|dish_portion |0.7257992517548667| 0.7297451976626956| 0.7234717973326836|
|dish_taste |0.741550961322326| 0.7729921893321348| 0.7181646276224011|
|dish_look |0.5880454784674226| 0.653362442800339| 0.5519640055596201|
|dish_recommendation |0.7306871485816995| 0.7708727861857518| 0.7039373170932841|
|others_overall_experience |0.5944163844272032| 0.7676540056028249| 0.5883530061244077|
|others_willing_to_consume_again |0.7105689860249018| 0.7341722872190272| 0.7130478713831332|

可以看到有些类别怎么提高都没有办法提到0.6。这些类别可能本身标注数据就不好，不好区分。

1. 我在训练10个模型的时候，使用了10-fold的方法，将训练和验证集放在一起，分成10份，训练了10个模型。
2. 尝试过使用一些数据增强的方法或者给类别加权重的方法来解决这些问题，但最后发现还是直接使用原始数据效果最好。这块我没有太深入去做。
3. 针对召回率特别低的类别（这种情况基本上是某个类别的四分类的结果里面，比如1的recall特别低），你可以考虑调整阈值，使得召回率提高一些，这样虽然会损失一些精度，但是整体的f1会提高。这方面属于模型训练好后的优化了，这方面我也没有太深入去做。

我这边做的数据预处理比较基本，分词+NER。其实还可以加入pos的信息。

**Comment by viewlei** [comment]
好的，再次感谢您的分享！
