### ISSUE TITLE
为什么做transpose操作

### ISSUE THREAD

**Issue by renmada** [xueyouluo/fsauor2018#4]
在elmo_encoder先对input做了transpose，然后transpose回来，这是为什么呢

**Comment by xueyouluo** [comment]
参考[tf.contrib.rnn.LSTMBlockFusedCell](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/LSTMBlockFusedCell)的使用方法。

**Comment by renmada** [comment]
还有个问题 Scalars and weight are learned variables
可以理解为这两个是trainable的吗

**Comment by xueyouluo** [comment]
是的

**Comment by renmada** [comment]
weight = tf.get_variable('weight', initializer=tf.constant(0.001))
self.final_outputs = weight * final_output

这里的weight是个标量，把final_output都放大或缩小同一个倍数有什么意义呢，不理解哦。

**Comment by xueyouluo** [comment]
这里是参考ELMO这篇论文的思路做的。
