### ISSUE TITLE
f1分布问题

### ISSUE THREAD

**Issue by chensuim** [xueyouluo/fsauor2018#5]
hello xueyouluo:
关于这个比赛，我看到数据十分不均横，但是比赛给出了macro f1, 我想问下的单独个例的f1分布是不是也不均衡？
是否单独对于一个方面的f1是否和该例的正例占比相关？比如“交通是否便利”下“未提及大概占了85%，负面和中性都只有3%左右，正面有10%左右，请问它们各自的f1是否有较大差别？是否正例比例大的更容易达到较高的f1？

谢谢
chensui

**Comment by xueyouluo** [comment]
关于这个问题，你可以参考我这个回答：https://github.com/xueyouluo/fsauor2018/issues/3#issuecomment-443961665

确实关系比较大，一般是三类比较均衡的话f1比较高。单单某个类别比例高的话都比较难得到比较高的f1。但是这也跟标签有关，有些标签本身比较容易区分，即使数据少也可以获得不错的f1，但是如果标签本身就比较难判断的话，即使数据多也不一定能获得比较高的f1。

**Comment by chensuim** [comment]
@xueyouluo 
谢谢
