### ISSUE TITLE
训练时间太长

### ISSUE THREAD

**Issue by googlx** [xueyouluo/fsauor2018#6]
老哥，请问一下您跑的时候训练时间大概多长？在8G内存/7代i5环境下，用默认的脚本跑了14个小时，还只跑完了2/3，有啥提升办法吗？谢谢！

**Comment by xueyouluo** [comment]
我这边使用的是1080TI机器，跑了大概7个小时结束。

 

发件人: Jeff Tsang <notifications@github.com>
答复: xueyouluo/fsauor2018 <reply@reply.github.com>
日期: 2019年6月20日 星期四 上午10:51
收件人: xueyouluo/fsauor2018 <fsauor2018@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [xueyouluo/fsauor2018] 训练时间太长 (#6)

 

老哥，请问一下您跑的时候训练时间大概多长？在8G内存/7代i5环境下，用默认的脚本跑了14个小时，还只跑完了2/3，有啥提升办法吗？谢谢！

**Comment by googlx** [comment]
谢谢：）
