### ISSUE TITLE
CUDA OOM on TESLA P40x2

### ISSUE THREAD

**Issue by SimZhou** [xueyouluo/fsauor2018#7]
**Environment:** 
linux Ubuntu 18.04
cuda10.1 with cudnn
tensorflow 1.15
python 3.6.10

**Issue:**
When running main.py to train the model, I got a cuda error in between: 
failed to allocate 4.00G (4294967296 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
How could that be while I am having 24*2=48Gigabytes of GPU memory?

===========================
Although, the training process seems to be working fine: 

![Training](http://uricc.ga/images/2020/01/09/72100445-9dc30400-335d-11ea-966b-a6bccd48c2a9.png)

(fsauor) root@4dde8abafae9:~# nvidia-smi
Thu Jan  9 19:50:59 2020       
+--------------------------------------------------------------------------------------+
| NVIDIA-SMI 418.39            Driver Version: 418.39             CUDA Version: 10.1     |
|-------------------------------------+----------------------+-------------------------+
| GPU  Name          Persistence-M  | Bus-Id            Disp.A |   Volatile Uncorr. ECC   |
| Fan    Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|=====================+==============+===============|
|   0  Tesla P40                        On   |  00000000:00:07.0 Off |                                Off |
| N/A   48C    P0        68W / 250W | 24370MiB / 24451MiB |            91%      Default |
+-----------------------------------+------------------------+-------------------------+
|   1  Tesla P40                        On   |   00000000:00:08.0 Off |                               Off |
| N/A   43C    P0      149W / 250W |   6770MiB / 24451MiB |            98%      Default |
+-----------------------------------+------------------------+--------------------------+
                                                                               
+----------------------------------------------------------------------------------------+
| Processes:                                                                                           GPU Memory |
|  GPU       PID   Type   Process name                                                          Usage      |
|=====================================================|
+-----------------------------------------------------------------------------------------+

**Comment by xueyouluo** [comment]
one 1080Ti(12G) GPU is enough for this model if you use the default settings. Does anyone else use the GPU at the same time? 24370MiB / 24451MiB is bigger than I thought.

**Comment by SimZhou** [comment]
Not sure of the reason (to the OOM error) but the model seems to be running fine, since I've just reached an early stop (at epoch 18), and the best F1-score is 0.7089

    # Eval loss 0.27121, f1 0.70520
    # current result -0.7052019417363357, previous best result -0.7089663459468849
    # No loss decrease, restore previous best model and set learning rate to half of previous one
    # Early stop, exit

Thanks for your codes anyway!

**Comment by SimZhou** [comment]
> one 1080Ti(12G) GPU is enough for this model if you use the default settings. Does anyone else use the GPU at the same time? 24370MiB / 24451MiB is bigger than I thought.

@xueyouluo Can I ask how long did it took you to train on an 1080Ti(12G)? Just curious about the performance difference here. (In total it took me 10-11 hrs here on 2 Tesla P40)

**Comment by xueyouluo** [comment]
> > one 1080Ti(12G) GPU is enough for this model if you use the default settings. Does anyone else use the GPU at the same time? 24370MiB / 24451MiB is bigger than I thought.
> 
> @xueyouluo Can I ask how long did it took you to train on an 1080Ti(12G)? Just curious about the performance difference here. (In total it took me 10-11 hrs here on 2 Tesla P40)

About 7 hrs.  Actually this code was not wrote for multi-gpus, you can train it with 1 gpu instead.

**Comment by SimZhou** [comment]
Cool! Thanks!
