### ISSUE TITLE
[HELP on debugging] Inference function not working properly

### ISSUE THREAD

**Issue by SimZhou** [xueyouluo/fsauor2018#8]
I am trying to make inferences with the model, however it requires the hparam 'embed_file', so when I run inference mode i got this error:

> ...
loading hparams from scripts/data/elmo_ema_0120\hparams
**Traceback (most recent call last):**
  File "main.py", line 260, in <module>
    inference(flags)
  File "main.py", line 81, in inference
    hparams = load_hparams(flags.checkpoint_dir,{"mode":'inference','checkpoint_dir':flags.checkpoint_dir+"/best_eval",'embed_file':None})
  File "C:\Users\yihua\models\fsauor2018\utils.py", line 166, in load_hparams
    hparams.set_hparam(k,v)
  File "C:\Users\yihua\Anaconda3\envs\tf1\lib\site-packages\tensorflow_core\contrib\training\python\training\hparam.py", line 523, in set_hparam
    setattr(self, name, _cast_to_type_if_compatible(name, param_type, value))
  File "C:\Users\yihua\Anaconda3\envs\tf1\lib\site-packages\tensorflow_core\contrib\training\python\training\hparam.py", line 176, in _cast_to_type_if_compatible
    raise ValueError(fail_msg)
**ValueError: Could not cast hparam 'embed_file' of type '<class 'str'>' from value None**

So I modified Line 81 of main.py from 
`hparams = load_hparams(flags.checkpoint_dir,{"mode":'inference','checkpoint_dir':flags.checkpoint_dir+"/best_eval",'embed_file':None})`
into
`hparams = load_hparams(flags.checkpoint_dir,{"mode":'inference','checkpoint_dir':flags.checkpoint_dir+"/best_eval",'embed_file':flags.embed_file})`
And then I run again with embed_file argument pointing the **embedding.txt** file, which succeeded on loading embedding but leads me to **another error**:
> unable to restore model with exception Can't load save_path when it is None.

Where can I add this parameter to? (since I don't find any file having this param?)

**Comment by SimZhou** [comment]
**I solved it myself.**
The error arrises because I somehow moved the `scripts/data/elmo_ema_0120` folder away so that the model checkpoints are not read by the script (by line 87 in main.py, `model.restore_model(sess)  #restore best solution`). 
That's a careless mistake.

**Comment by xueyouluo** [comment]
great!
