### ISSUE TITLE
Is this the detailed structure of the model?

### ISSUE THREAD

**Issue by SimZhou** [xueyouluo/fsauor2018#9]
Sorry to ask about this since it should be written in the code, but I am really not so familiar with Tensorflow so I think it would be faster to ask about this directly. 

So in the decoder part of the model, I am assuming a structure like this: 
![](http://uricc.ga/images/2020/01/16/_20200116143023.png)
Then the process is carried on for 20 steps to get 20 outputs?

So in the attention part which ![](http://latex.codecogs.com/gif.latex?u_s) is it using to calculate the attention score? Is it a self-attention which uses the output of each LSTM cell as a query?

And further more, how is the outputs from different layers of encoders (elmo) fed into the decoder LSTMs (![](http://latex.codecogs.com/gif.latex?s_1,s_2,\cdots{s_L}))? Is it a simple concatenation of those layers?

Thanks in advance!

**Comment by SimZhou** [comment]
As far as I understand, don't know if this is the right case: 
[Structure](https://uricc.ga/images/2020/01/16/_20200116164817.jpg)
![Structure](http://uricc.ga/images/2020/01/16/_20200116164817.jpg)

**Comment by xueyouluo** [comment]
```
Then the process is carried on for 20 steps to get 20 outputs?
```
 yes

---

```
# [20]
features = tf.range(self.hparams.feature_num,dtype=tf.int32)
feature_embedding_var = create_embedding("feature_embedding", self.hparams.feature_num, self.hparams.embedding_size)
# [20 * embedding_size]
feature_embedding = tf.nn.embedding_lookup(feature_embedding_var, features)
# [batch * 20 * embedding_size]
self.feature_embedding = tf.tile(tf.expand_dims(feature_embedding,axis=0),[self.batch_size,1,1])
```
The inputs of decoder are not fixed, they are learnable values.

---
You structure is almost right, embedding is also added to the final encoder states. you can check the [model structure](https://github.com/xueyouluo/fsauor2018#model-architecture) I drawn.

**Comment by SimZhou** [comment]
Understood, Thanks for the explanation!
